%% main 

% load off target data 
[original_sites, off_target_sites, scores, copy_number, pam_sites] = load_off_target_data();

% load primary data 
[average_binding_data, average_sgRNA_Tarasava, average_host_Tarasava] = ...
            load_avg_data;
        
%% initialization of parameters
[r_crRNA, Delta_crRNA, r_Cas9, Delta_Cas9, Delta_complex, k_I, k_f, Lambda, D, V, k_d, k_c, mu] = initialize_parameters();
ODE_parameters = [r_crRNA, Delta_crRNA, r_Cas9, Delta_Cas9, Delta_complex, k_I, k_f, Lambda, D, V, k_d, k_c, mu]';
integration_time = (600); % only consider the first 10 minutes  
integration_accuracy = 1; % mutiple of 1 evaluation per minute
Cas_concentration = 25; % concentration of Cas molecule injected to start nanoleters
crRNA_concentration = 25; % concentration of crRNA molecule injected to start nanoleters
on_target_copy_number = 1; % number of duplicates of a host site (off target)
off_target_copy_number = ones(length(scores)+1,1); % number of duplicates of a host site (off target)
percent_off_target = 0.0; % written as percentage 
%[GG, GC, GA, GT, CG, CC, CA, CT, AG, AC, AA, AT, TG, TC, TA, TT ]; 
% second value is the gRNA first is the host 
match_mismatch_params = -1*[-1.97, -2.70, -1.66, -2.04,...
                             -1.44, -1.97, -0.78, -1.29,...
                             -1.29, -2.04, -1.04, -1.27,...
                             -0.78, -1.66, -0.12, -1.04]'; 
% ['ATG', 'GAG', 'GGA', 'GAA', 'GAT']
pam_parameters = -1*[-6.6, -6.9, -9.4, -6.8, -6.9]/max(-1*[-6.6, -6.9, -9.4, -6.8, -6.9]);
% train model parameters  
max_iterations = .5*10^4;
Number_of_Nucleotides = 32;
stopping_Tol = .05;
off_target_weight = .00; % the error from off targeting will be worth 1/10 of the true data
old_info = 'model_parameters_free.mat'; 

%% train 
% call function
use_old = 1;
[model_parameters, just_trained] = train_model(average_host_Tarasava, average_sgRNA_Tarasava,...
                            average_binding_data, max_iterations,...
                            use_old, Number_of_Nucleotides,...
                            old_info, ODE_parameters, off_target_sites,...
                            integration_time,integration_accuracy,...
                            Cas_concentration, crRNA_concentration, ...
                            on_target_copy_number, off_target_copy_number, pam_sites, ...
                            percent_off_target, off_target_weight, stopping_Tol);
%save parameters
model_parameters_free = model_parameters; 
save(old_info, 'model_parameters_free')
disp(model_parameters_free)

%% test values
add_plot = 1;
load(old_info)
percent_off_target = 1;
[error, P_on_target, P__binding_rate] = test_model(average_host_Tarasava, average_sgRNA_Tarasava,...
        average_binding_data, just_trained, Number_of_Nucleotides, ...
                            off_target_sites, integration_time, integration_accuracy,...
                            Cas_concentration, crRNA_concentration, on_target_copy_number, ...
                            off_target_copy_number, off_target_weight, ODE_parameters, ...
                            pam_sites, add_plot);
    
close all
% accuracy plot on real data
figure(1)   
b = bar(linspace(1,length(P__binding_rate),length(P__binding_rate)),[P__binding_rate average_binding_data]);
b(2).FaceColor = 'r';
title('observed and predicted binding')
xlabel('distance from current position backward')
ylabel('function evaluation')
title('True versus Predicted Bind ing within dCas9 System')
xlabel('Data Point')
ylabel('Predicted Binding')

%% Hold one out cross validation
[total_error_per_point, indv_error_per_point, trained_parameters, total_parameters] ...
    = hold_one_out_cross_validation(average_host_Tarasava,average_sgRNA_Tarasava,...
                            average_binding_data, max_iterations,...
                            use_old, Number_of_Nucleotides,...
                            old_info, ODE_parameters, off_target_sites,...
                            integration_time,integration_accuracy,...
                            Cas_concentration, crRNA_concentration, ...
                            on_target_copy_number, off_target_copy_number, ...
                            percent_off_target, off_target_weight, stopping_Tol);

                        
%% ten fold cross validation  
[total_error_per_point, indv_error_per_point, trained_parameters, total_parameters] ...
    = hold_one_out_cross_validation(average_host_Tarasava,average_sgRNA_Tarasava,...
                            average_binding_data, max_iterations,...
                            use_old, Number_of_Nucleotides,...
                            old_info, ODE_parameters, off_target_sites,...
                            integration_time,integration_accuracy,...
                            Cas_concentration, crRNA_concentration, ...
                            on_target_copy_number, off_target_copy_number, ...
                            percent_off_target, off_target_weight, stopping_Tol);
                        